### ISSUE TITLE
Unable to build on Fedora 36 with GCC 12.0.1

### ISSUE THREAD

**Issue by ProjectSynchro** [catsout/wallpaper-engine-kde-plugin#154]
**Describe the bug**<br/>
While attempting to build this project on Fedora 36 I ran into a few issues. At first glace this almost looks like some missing #includes.

I last attempted to build commit 9a2f3aa0594c97ce49dcae3f0217ca8f70822240.

**System Information**
- Kde: 5.24.4
- Qt: 5.15.3
- OS: Fedora 36 Beta

**Additional context**<br/>
Some errors of note.

```cc
In file included from /home/synchro/Documents/GitStuff/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/Vulkan/include/Vulkan/StagingBuffer.hpp:3,
                 from /home/synchro/Documents/GitStuff/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/Vulkan/StagingBuffer.cpp:1:
/home/synchro/Documents/GitStuff/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/./Utils/span.hpp: In constructor ‘constexpr Span<T>::Span(const Range&)’:
/home/synchro/Documents/GitStuff/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/./Utils/span.hpp:33:51: error: ‘data’ is not a member of ‘std’
   33 |     constexpr Span(const Range& range) : ptr{std::data(range)}, num{std::size(range)} {}
      |                                                   ^~~~
/home/synchro/Documents/GitStuff/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/./Utils/span.hpp:33:74: error: ‘size’ is not a member of ‘std’; did you mean ‘size_t’?
   33 |     constexpr Span(const Range& range) : ptr{std::data(range)}, num{std::size(range)} {}
      |                                                                          ^~~~
      |                                                                          size_t

```

```cc
In file included from /home/synchro/Documents/GitStuff/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/Looper/Looper.cpp:1:
/home/synchro/Documents/GitStuff/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/Looper/include/Looper/Looper.hpp:163:35: error: field ‘m_items’ has incomplete type ‘std::array<wallpaper::looper::Message::Item, 64>’
  163 |     std::array<Item, MaxNumItems> m_items;
      |                                   ^~~~~~~

```

**Comment by catsout** [comment]
Fixed.
